name: Build and Deploy to VPS Perso

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: |
        npm run build
        cp package.json dist/server/

    - name: Deploy to VPS perso via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_IONOS }}
        username: ${{ secrets.USER_IONOS }}
        key: ${{ secrets.SSH_PRIVATE_KEY_IONOS }}
        source: "dist/*"
        target: "/var/www/portfolio/"
        strip_components: 1
        rm: false
        overwrite: true
        debug: true

    - name: Install production dependencies on VPS perso
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_IONOS }}
        username: ${{ secrets.USER_IONOS }}
        key: ${{ secrets.SSH_PRIVATE_KEY_IONOS }}
        
        script: |
          cd /var/www/portfolio/server
          npm ci --omit=dev
          npm install astro
          npm install send server-destroy
          PORT=8088 pm2 restart portfolio || PORT=8088 pm2 start entry.mjs --name portfolio
